### ISSUE TITLE
Specification does not justify its necessity for existence

### ISSUE THREAD

**Issue by IanKemp** [w3c/webappsec-secure-contexts#2]
Take the Geolocation API as an example, in particular section 4 http://www.w3.org/TR/geolocation-API/#security which explicitly states the following:

"A conforming implementation of this specification must provide a mechanism that protects the user's privacy and this mechanism should ensure that no location information is made available through this API without the user's express permission. User agents must not send location information to Web sites without the express permission of the user. User agents must acquire permission through a user interface..."

Any user agent that conforms to the Geolocation specification should therefore, to my mind, be adequately protecting their users' privacy. This Secure Contexts specification implicitly makes the determination that Geolocation-conforming user agents are a security issue, but does not explain how or why it makes that determination, and hence does not explain why this specification is necessary.

If this specification's existence cannot be justified, then it should cease to exist. Considering user-agent vendors e.g. Chromium https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins are implementing this specification by deprecating features in "insecure" contexts, the impact of this specification on end-users cannot be underestimated.

**Comment by jwatt** [comment]
I agree, the text doesn't currently explain why using secure contexts is important and the issue wasn't immediately obvious to me. Hopefully the following description clarifies things, and something like it can be integrated into the spec.

It should be fairly obvious that a plain HTTP (unauthenticated and unencrypted) page could have content injected into it by a network attacker to send any geolocation data that the page obtains to the attacker, or even to make a request for that data if the page doesn't already do so. The obvious solution is to require the page that uses this or similar features to use HTTPS, but it's not as simple as that. Requiring HTTPS just for the page that uses a feature is easily worked around by content authors. Someone can create a website that provides other sites with a service whereby they can embed an HTTPS page using, say, an iframe, and that HTTPS page will make the request for geolocation data on its behalf. The service site can allow an HTTP page that embeds its HTTPS page to access the HTTPS page using CORS. Content authors who don't want to go to the trouble of using HTTPS on their site can then just embed the service site's HTTPS page and, "problem" solved, it seems. Unfortunately this workaround completely nullifies the whole point of the simple HTTPS restriction. Attackers can inject code into the HTTP page and, since CORS gives access to the HTTPS iframe, the HTTPS iframe and user data is now vulnerable to attack.

Secure contexts are a refinement on the simple HTTPS restriction to prevent content authors who are ignorant of the security consequences of the workaround described above from unwittingly making their site and users vulnerable to attack.

**Comment by jwatt** [comment]
Chatting to Mike, he points out that https://w3c.github.io/webappsec-secure-contexts/#ancestors is intended to describe why we need 'secure contexts' rather than just a simple HTTPS restriction. Talking with him now about how the text could be reordered and changed to make this info clearer.

**Comment by mikewest** [comment]
I think we've made changes to clarify the spec's purpose and intent. Thanks for the report!
