### ISSUE TITLE
Figure out how to manage normative dependencies to WHATWG HTML for features not in W3C HTML for CR/REC

### ISSUE THREAD

**Issue by hillbrad** [w3c/webappsec-secure-contexts#9]

**Comment by hillbrad** [comment]
@wseltzer

**Comment by mikewest** [comment]
I'll be sending out a new CfC shortly. It would be helpful to get this hammered out for the ~3 references I need from WHATWG's HTML. :)

**Comment by mikewest** [comment]
Ping. I'm very wary of referencing W3C's "HTML 5.1" in its current state. If we'd like to move this document to CR, clarity on these kinds of dependencies would be appreciated.

**Comment by wseltzer** [comment]
@mikewest @hillbrad -- @plehegar, let's talk

**Comment by annevk** [comment]
Somewhere public, I hope?

**Comment by wseltzer** [comment]
@annevk likely public-webappsec

**Comment by mikewest** [comment]
@wseltzer: Sorry for the _substantial_ delay; I got distracted.

The CR proposed at https://lists.w3.org/Archives/Public/public-webappsec/2016Jul/0032.html mostly points to HTML 5.1 (though I haven't reviewed the diff from the WHATWG document, and as I noted in the F2F, I don't actually intend to do so), and has a few normative references to WHATWG specs in places where the W3C versions are missing concepts:

1.  W3C's URL hasn't been updated since 2014 and points off to https://url.spec.whatwg.org/, so that's what I'm using for `URL`, and a `URL`'s "scheme" and "origin".

2.  W3C's HTML doesn't have `WindowOrWorkerGlobalScope` (https://github.com/w3c/html/issues/522), `creator context security` (https://github.com/w3c/html/issues/524), or `noopener` (https://github.com/w3c/html/issues/523).

Note also that WEBWORKERS hasn't been updated since last September, and I haven't reviewed the diff to https://html.spec.whatwg.org/multipage/workers.html. I know that the WHATWG document is wildly divergent at this point, as the whole loading infrastructure has shifted. It would be lovely if there was a plan for removing or updating that document.

**Comment by mikewest** [comment]
Ping. :)

**Comment by equalsJeffH** [comment]
another ping.

**Comment by mikewest** [comment]
I think HTML picked up the pieces I need. W3C's Workers spec still has one outstanding issue (w3c/workers#6).

Again, I haven't reviewed any of that text for differences from the WHATWG doc; I've only verified that there's a valid link target with a reasonable name.

**Comment by annevk** [comment]
This is a solved problem these days.
